spring:
  servlet:
    multipart:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: meodev12@gmail.com
    password: uwyq ryrr axut ayeq

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: my-spring-boot

  datasource:
    url: jdbc:postgresql://localhost:5433/home_service_system
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

app:
  baseUrl: http://localhost:8081

server:
  port: 8081

google:
  recaptcha:
    secret-key: "6LepKQ0rAAAAAAFrDRjzJ9qkKP70hhNgOzgoi_1Z"